import re
import requests
from datetime import datetime

# 远程源地址
SOURCE_URL = "https://raw.githubusercontent.com/sggc/SDU-IPTV-NEW/refs/heads/main/playlist.m3u"

def fetch_source():
    try:
        resp = requests.get(SOURCE_URL, timeout=10)
        resp.raise_for_status()
        return resp.text.splitlines(keepends=True)  # 保留换行符
    except Exception as e:
        print(f"❌ 获取源文件失败: {e}")
        exit(1)

def process():
    lines = fetch_source()
    processed_lines = []
    rtp_lines = []

    # 用于临时存储特殊条目
    cgtn_channels = []
    cctv4_eu_am = []
    shandong_jingji = None
    other_lines = []
    in_channels = []

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith('#EXTINF') and 'tvg-name=' in line:
            url_line = lines[i + 1] if i + 1 < len(lines) else '\n'

            # 提取频道信息
            name_match = re.search(r'tvg-name="([^"]+)"', line)
            group_match = re.search(r'group-title="([^"]+)"', line)
            if not name_match:
                in_channels.append((line, url_line))
                i += 2
                continue

            name = name_match.group(1)

            # === 特殊处理 CGTN → 其他频道 ===
            if name.startswith("CGTN"):
                line = re.sub(r'group-title="[^"]+"', 'group-title="其他频道"', line)

            # === 特殊处理：捕获山东经济广播 ===
            if name == "山东经济广播":
                line = re.sub(r'group-title="[^"]+"', 'group-title="广播频道"', line)
                shandong_jingji = (line, url_line)
                i += 2
                continue  # 先不加入当前列表

            # === 捕获 CCTV4 欧美 ===
            if name in ["CCTV4欧洲", "CCTV4美洲"]:
                cctv4_eu_am.append((line, url_line))
                i += 2
                continue

            # === 修改 catchup-source 参数 ===
            catchup_pattern = r'(catchup-source="[^"]+\?tvdr=)\{utc:YmdHMS\}GMT-\{utcend:YmdHMS\}GMT'
            new_line = re.sub(
                catchup_pattern,
                r'\1${(b)yyyyMMddHHmmss}GMT-${(e)yyyyMMddHHmmss}GMT&r2h-seek-offset=-28800',
                line
            )

            # === 构建 RTP 版本（HTTP 代理）===
            rtp_url = url_line.strip()
            if rtp_url.startswith('rtsp://'):
                rtp_url = re.sub(r'^rtsp://', 'http://192.168.100.1:5140/rtsp/', rtp_url)

            rtp_catchup = re.sub(
                r'(catchup-source="rtsp://)',
                r'catchup-source="http://192.168.100.1:5140/rtsp/',
                new_line
            )

            processed_lines.append(new_line)
            processed_lines.append(url_line)

            rtp_lines.append(rtp_catchup)
            rtp_lines.append(rtp_url + '\n')

            in_channels.append((new_line, url_line))
            i += 2
        else:
            processed_lines.append(line)
            rtp_lines.append(line)
            other_lines.append(line)
            i += 1

    # === 开始重组频道顺序 ===
    final_catchup = []
    final_rtp = []

    # 添加头部注释
    final_catchup.append(f"#EXTM3U\n")
    final_catchup.append(f"# Generated by GitHub Actions\n")
    final_catchup.append(f"# Source: {SOURCE_URL}\n")
    final_catchup.append(f"# Processed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    final_catchup.append(f"# 处理规则已应用\n\n")

    final_rtp.extend(final_catchup)

    # 1. 添加 #EXTINF:CCTV1
    for line, url in in_channels:
        if 'tvg-name="CCTV1"' in line:
            final_catchup.append(line)
            final_catchup.append(url)
            break

    # 2. 插入复制的“山东卫视”并改为央视频道
    for line, url in in_channels:
        if 'tvg-name="山东卫视"' in line and 'group-title="山东频道"' in line:
            new_line = re.sub(r'group-title="[^"]+"', 'group-title="央视频道"', line)
            final_catchup.append(new_line)
            final_catchup.append(url)
            break

    # 3. 继续添加其他央视频道（除CCTV4欧/美）
    for line, url in in_channels:
        name = re.search(r'tvg-name="([^"]+)"', line)
        if not name:
            continue
        name = name.group(1)
        if "CCTV" in name and name not in ["CCTV4欧洲", "CCTV4美洲"]:
            if line not in final_catchup:
                final_catchup.append(line)
                final_catchup.append(url)

    # 4. 添加山东频道（直到“山东少儿”）
    shandong_kids_found = False
    for line, url in in_channels:
        group = re.search(r'group-title="([^"]+)"', line)
        if group and group.group(1) == "山东频道":
            final_catchup.append(line)
            final_catchup.append(url)
            if "山东少儿" in line:
                shandong_kids_found = True
                # 此处插入 CCTV4 欧/美
                for c_line, c_url in cctv4_eu_am:
                    final_catchup.append(c_line)
                    final_catchup.append(c_url)
    if not shandong_kids_found and cctv4_eu_am:
        # 如果没找到，就最后插入
        for c_line, c_url in cctv4_eu_am:
            final_catchup.append(c_line)
            final_catchup.append(c_url)

    # 5. 添加其余频道
    for line, url in in_channels:
        name = re.search(r'tvg-name="([^"]+)"', line)
        if not name:
            continue
        name = name.group(1)
        if name not in ["CCTV4欧洲", "CCTV4美洲", "山东经济广播"] and \
           "山东频道" not in re.search(r'group-title="([^"]+)"', line).group(1):
            if line not in final_catchup:
                final_catchup.append(line)
                final_catchup.append(url)

    # 6. 添加山东经济广播到最后
    if shandong_jingji:
        final_catchup.append(shandong_jingji[0])
        final_catchup.append(shandong_jingji[1])

    # === 构建 RTP 文件（同步结构）===
    final_rtp = [l for l in final_catchup]  # 复制结构
    # 但替换所有 URL 和 catchup-source 为 HTTP
    temp_rtp = []
    j = 0
    while j < len(final_rtp):
        line = final_rtp[j]
        if j + 1 < len(final_rtp) and line.startswith('#EXTINF'):
            url_line = final_rtp[j + 1]
            # 替换主 URL
            new_url = url_line.strip()
            if new_url.startswith('rtsp://'):
                new_url = re.sub(r'^rtsp://', 'http://192.168.100.1:5140/rtsp/', new_url)
            # 替换 catchup-source
            new_line = re.sub(
                r'(catchup-source="rtsp://)',
                r'catchup-source="http://192.168.100.1:5140/rtsp/',
                line
            )
            temp_rtp.append(new_line)
            temp_rtp.append(new_url + '\n')
            j += 2
        else:
            temp_rtp.append(line)
            j += 1
    final_rtp = temp_rtp

    # 写出文件
    with open('unicast-catchup.m3u', 'w', encoding='utf-8', newline='') as f:
        f.writelines(final_catchup)

    with open('unicast-rtp.m3u', 'w', encoding='utf-8', newline='') as f:
        f.writelines(final_rtp)

    print("✅ 文件生成完成：unicast-catchup.m3u 和 unicast-rtp.m3u")


if __name__ == '__main__':
    process()
